### PR TITLE
Color Identification using OpenCV

### PR DESCRIPTION
**Pull request by vishvarana**
Related Issue
Color detection in images using OpenCV

√ DevIncept Participant
 √ Contributor

Closes: #27 

Describe the changes you've made
I have added a new project that detects colors in  a given image with their proportions using a pie-chart as well as finds those images from a lot which has the mentioned color that we require.

Type of change
What sort of change have you made:
It is a new feature to this repo.

    Bug fix (non-breaking change which fixes an issue)
 √ New feature (non-breaking change which adds functionality)
    Code style update (formatting, local variables)
    Breaking change (fix or feature that would cause existing functionality to not work as expected)
    This change requires a documentation update

How Has This Been Tested?
Describe how have you verified the changes made
I have written code in jupyter notebook to test the code on a particular image and return a pie chart with proportion of its colors. Also I have tested the code by bringing out the images with color we ask for. 

Checklist:
 √My code follows the guidelines of this project.
 √I have performed a self-review of my own code.
 √I have commented my code, particularly wherever it was hard to understand.
 √I have made corresponding changes to the documentation.
 √My changes generate no new warnings.
 √I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the project structure given. And also there is template for README file to let participants know how it should be written. @vishvarana

**Comment by prathimacode-hub** [comment]
First of all read the README and CONTRIBUTING GUIDELINES of the project. Then you would know the project structure and changes you have to make. @vishvarana

**Comment by vishvarana** [comment]
Renamed according to snake_case and updated README according to the format.

**Comment by vishvarana** [comment]
I have to make a different branch right? Rest all is done I guess.
Please let me know I am new to this

**Comment by vishvarana** [comment]
I am opening a new pull request and closing this one because of conflicts

**Comment by prathimacode-hub** [comment]
But you should never close issues or PR from your end. Not everyone would take it positive. Just letting you know so that you don't do it in future. Instead you could had said it to me to close it. @vishvarana

**Pull request closed without merging**
