### PR TITLE
Introduction To Pandas

### PR DESCRIPTION
**Pull request by suy1968**
## Introduction To Pandas

- Info about the Introduction To Pandas

- [x] DevIncept Participant 
- [x] Contributor

Closes: #34 

### Describe the changes you've made
This issue will help readers in giving all the guidance that one needs to learn about pandas. Tutorial to pandas and how it's applied using sample code.
The main intention of this repo is to educate beginners with all the concepts related to data science so that they could feel confident to apply these things learned in practical exposure.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The project folder should be as "Introduction to Pandas" 
The project file should be as "introduction_to_pandas.ipynb"
Instead of 2 separate project files, as you had used pandas libarary in merging dataframes, you can add this up in "introduction_to_pandas.ipynb" project file as a continuation.

Kindly do these changes. @suy1968

**Comment by suy1968** [comment]
> Changes to be done:
> The project folder should be as "Introduction to Pandas"
> The project file should be as "introduction_to_pandas.ipynb"
> Instead of 2 separate project files, as you had used pandas libarary in merging dataframes, you can add this up in "introduction_to_pandas.ipynb" project file as a continuation.
> 
> Kindly do these changes. @suy1968

Maam Please once again  i do all things one things donot do that is Introduction to Pandas (i write this Introduction_To_Pandas)
Please merge this time Maam , I donot make mistake another time @prathimacode-hub

**Comment by prathimacode-hub** [comment]
> > Changes to be done:
> > The project folder should be as "Introduction to Pandas"
> > The project file should be as "introduction_to_pandas.ipynb"
> > Instead of 2 separate project files, as you had used pandas libarary in merging dataframes, you can add this up in "introduction_to_pandas.ipynb" project file as a continuation.
> > Kindly do these changes. @suy1968
> 
> Maam Please once again i do all things one things donot do that is Introduction to Pandas (i write this Introduction_To_Pandas)
> Please merge this time Maam , I donot make mistake another time @prathimacode-hub

I didn't get you, what you meant to say? @suy1968

**Comment by suy1968** [comment]
> > > Changes to be done:
> > > The project folder should be as "Introduction to Pandas"
> > > The project file should be as "introduction_to_pandas.ipynb"
> > > Instead of 2 separate project files, as you had used pandas libarary in merging dataframes, you can add this up in "introduction_to_pandas.ipynb" project file as a continuation.
> > > Kindly do these changes. @suy1968
> > 
> > 
> > Maam Please once again i do all things one things donot do that is Introduction to Pandas (i write this Introduction_To_Pandas)
> > Please merge this time Maam , I donot make mistake another time @prathimacode-hub
> 
> I didn't get you, what you meant to say? @suy1968

Maam please check once @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Great going. I appreciate your efforts you put up in your PR. Keep rising. 🙌🤩@suy1968

**Comment by prathimacode-hub** [comment]
Kindly fill the form for your PR's to get counted. You had filled only once and that too wrong PR number. 
You need to fill it up for your 2pr's: Introduction to Numpy, Introduction to Pandas. That is PR no's : 117 and 118. Fill them up before tomorrow as I had to send scores to the team. 1 PR = 1 Filled Form. It means in total 2 forms with PR links I had to get them. @suy1968

**Comment by suy1968** [comment]
> Kindly fill the form for your PR's to get counted. You had filled only once and that too wrong PR number.
> You need to fill it up for your 2pr's: Introduction to Numpy, Introduction to Pandas. That is PR no's : 117 and 118. Fill them up before tomorrow as I had to send scores to the team. 1 PR = 1 Filled Form. It means in total 2 forms with PR links I had to get them. @suy1968

Done Maam @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Have you done it for both PR's. @suy1968

**Comment by suy1968** [comment]
> Have you done it for both PR's. @suy1968

Yes Ma'am, Introduction to numpy and pandas

**Comment by prathimacode-hub** [comment]
> > Have you done it for both PR's. @suy1968
> 
> Yes Ma'am, Introduction to numpy and pandas

Cool.

**Pull request merged**
