### PR TITLE
NLP based Chatbot

### PR DESCRIPTION
**Pull request by hrugved06**
## NLP based Chatbot #14 

- Created and implemented the NLP based chatbot with a proper documentation 

- [x] DevIncept Participant 
- [x] Contributor

Closes: #14 

### Describe the changes you've made

- Created and implemented the chatbot which chats with you based on the transcript you used in the training. 
- Added dataset in the Dataset folder and also added the required files.
- Also, README is added with a proper and detailed explanation. 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Once you run the model and start testing you get an option for the "User" input, where you can test and chat with the bot.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Images should be present in "Images" folder in "NLP Based Chatbot".
The project file should be titled as "discord_bot.ipynb".
In README.md, in working conditions along with image source you had given to explain each step, also elaborate the step in words. 

Kindly do these changes. @hrugved06

**Review by prathimacode-hub — APPROVED** [review]
This is a fab A++ work. Amazingly showcased your efforts and very well explained. PR is approved. Congrats. and welcome to the repo officialy. Yayy. Kudos. ✨🎉👏@hrugved06

**Comment by hrugved06** [comment]
Hey @prathimacode-hub, I have done all the requested changes, please do check.
Thank you :-D

**Review by prathimacode-hub — APPROVED** [review]
Picture perfect and clean PR. Outstanding and A++ work. You had done a fab job in explaining and representing the NLP Chatbot. Kudos to your efforts. One of the best PR in this repo. Congrats on your first PR. Welcome to repo officially. Yayy. ✨🎉👏@hrugved06

**Pull request merged**
