### PR TITLE
Convolution Neural Networks

### LINKED ISSUE #98: Convolution Neural Networks
Hey DCP participants, good to see you here

This issue will helps readers in giving all the guidance that one needs to learn about Introduction to Convolution Neural Networks. Tutorial to Convolution Neural Networks and how it's applied using sample code.

"Project Title" should be the "Issue Title" mentioned here.

If you like to work on this issue, follow the given guidelines for code as well as for the README. You have to be as elaborative as possible. Make sure you also maintain the project structure provided. Just comment and get it assigned. Issues are alloted on FCFS basis.

The main intention of this repo is to educate beginners with all the concepts related to datascience so that they could feel confident to apply these things learnt in practical exposure.

Enjoy your open source journey ahead. 😎

### PR DESCRIPTION
**Pull request by avinash-218**
## Related Issue 

- Info about the related issue 

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

Closes: #98 

### Describe the changes you've made

- Added notebook
- Added README.md
- Added stored weights
- Added model architecture image
- added Json file

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I verified the notebook by running successfully

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whenever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly check on to project structure to correct changes needed. @avinash-218

**Comment by avinash-218** [comment]
> Kindly check on to project structure to correct changes needed. @avinash-218

Can you please explain ma'am

**Comment by avinash-218** [comment]
@prathimacode-hub Please check now ma'am

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

README.md can be more elaborative
In .ipynb file, add short intro at start and overall summary at the end
In "requirements.txt" file, add all the libraries that have been imported into this topic. 

Kindly work on it. @avinash-218

**Comment by prathimacode-hub** [comment]
Changes not yet done? @avinash-218

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly elaborate your README file, it has no detailing on Convolutional Neural Networks briefly. Kindly do that. @avinash-218

**Review by prathimacode-hub — APPROVED** [review]
README can be briefer but still I consider with less time on fest and also your efforts don't get wasted as no response from you yet. You had done a great work. PR approved. 🙌👌@avinash-218

**Pull request merged**
