### PR TITLE
Color Detection using OpenCV

### PR DESCRIPTION
**Pull request by vishvarana**
Do let me know if anything is not right

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Your PR is conflicting. And this PR doesn't show up any files. I guess you have to recreate the PR. Send all the files except README.md. @vishvarana

**Comment by vishvarana** [comment]
I have rebased the last branch to a new one and deleted not required files.
Files required are already present in this branch but not reflecting in the pull request

**Comment by prathimacode-hub** [comment]
Oops, but its showing conflict here. @vishvarana

**Comment by vishvarana** [comment]
I guess I will have to make a new branch so a new PR from scratch so please close this PR

**Comment by prathimacode-hub** [comment]
Ok, got you. I shall close this PR. Come up with a new PR on the same. @vishvarana

**Pull request closed without merging**
