### PR TITLE
Object detection using Tensorflow

### PR DESCRIPTION
**Pull request by shivani6320**
## Object Detection using Tensorflow
- The main purpose of this project is to detect objects in images using pre-trained SSD MobileNet model from tensorflow API.

- [x] DevIncept Participant 
- [x] Contributor

Closes: #9 

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Can you add more references in README.md for beginners. @shivani6320

**Comment by shivani6320** [comment]
@prathimacode-hub , requested changes has been done. Please check.

**Review by prathimacode-hub — APPROVED** [review]
Whooaa, amazing work Shivani. As usual, your efforts are seen here. Outstandingly represented the issue you had taken. 100% justice to the core. Keep acing up. 🤩🙌🎇@shivani6320

**Comment by shivani6320** [comment]
@prathimacode-hub Thank you so much for appreciating. This motivates me to keep contributing.✨

**Comment by prathimacode-hub** [comment]
You deserve this appreciation and great going. 🙌@shivani6320

**Comment by prathimacode-hub** [comment]
Kindly fill the form with your PR link. Your response hadn't come yet. @shivani6320

**Comment by shivani6320** [comment]
@prathimacode-hub Can you please share the form link here?

**Comment by prathimacode-hub** [comment]
Here is the link : https://docs.google.com/forms/d/e/1FAIpQLSfLNWo_eTLYVzSfijMug_fGAjQmhHXINA3kp4Eig3pzQXJacg/viewform

**Comment by shivani6320** [comment]
@prathimacode-hub I have filled the form.

**Pull request merged**
