### PR TITLE
Data Preprocessing in ML

### PR DESCRIPTION
**Pull request by dilroseR**
### Related Issue
- Info about the related issue

 - [x] DevIncept Participant
  - [x] Contributor

Closes: #110 

### Describe the changes you've made
Created .ipynb files and a readme.md file explaining data preprocessing in ml
data preprocessing in:
- numerical data
- categorical data

### Type of change

 - [x] New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
Tested manually on my PC

### Checklist:
  - [x] My code follows the guidelines of this project.
  - [x] I have performed a self-review of my own code.
 - [x]  I have commented my code, particularly wherever it was hard to understand.
  - [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by dilroseR** [comment]
can you review this pr?

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Follow the README template given. It needs more data and elaboration to justify this repo. 
Add all the .csv files in "Dataset" folder created.
Add appropriate comments in code files to get good understanding of the topic.

Kindly do these changes. @dilroseR

**Comment by prathimacode-hub** [comment]
Kindly do the changes. @dilroseR

**Comment by dilroseR** [comment]
done

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
This repo focuses beginners so we need to  include all information in README.md
Add advantages, disdvantages, applications, screenshot of output or visualizations and references. Add good number of references for beginners to understand this concept briefer. 

Kindly do these changes. @dilroseR

**Comment by dilroseR** [comment]
> This repo focuses beginners so we need to include all information in README.md
> Add advantages, disdvantages, applications, screenshot of output or visualizations and references. Add good number of references for beginners to understand this concept briefer.
> 
> Kindly do these changes. @dilroseR

i've created my own dataset and applied all the coding by my own. i don't have any reference . rest all i can do. kindly excuse me with the reference part

**Comment by prathimacode-hub** [comment]
> > This repo focuses beginners so we need to include all information in README.md
> > Add advantages, disdvantages, applications, screenshot of output or visualizations and references. Add good number of references for beginners to understand this concept briefer.
> > Kindly do these changes. @dilroseR
> 
> i've created my own dataset and applied all the coding by my own. i don't have any reference . rest all i can do. kindly excuse me with the reference part

References means not the ones  you referred, references means what beginners can refer for knowing the concepts in more deep. @dilroseR

**Comment by dilroseR** [comment]
updated

**Review by prathimacode-hub — APPROVED** [review]
Yup, PR approved. Great job. Well done. Your efforts are appreciated. Kindly don't forget to fill up the form for the same using right PR link. @dilroseR

**Pull request merged**
