### PR TITLE
Introduction to Numpy

### PR DESCRIPTION
**Pull request by suy1968**
## Introduction to Numpy

- Guidance that one needs to learn about NumPy Implementation.

- [x] DevIncept Participant 
- [x] Contributor

Closes:  #117 

### Describe the changes you've made

The main intention of this repo is to educate beginners with all the concepts related to data science so that they could feel confident to apply these things learned in practical exposure.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Helps readers in giving all the guidance that one needs to learn about NumPy. Tutorial to NumPy using Sample codes. 

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Just a suggestion, to do changes you don't have to create new PR. You can make changes directly. Add or remove files you need in your forked repository and push changes again, that would auotmatically correct it up right. 👍@suy1968

**Review by prathimacode-hub — APPROVED** [review]
You had done an amazing work. I highly appreciate your efforts put up. Congo, your PR is approved. Keep going. 👏👌@suy1968

**Comment by prathimacode-hub** [comment]
Oops,  I didn't check properly, got mistaked. You haven't created a project folder of "Introduction to Numpy" and uploaded all the files instead you had placed it all individually in Machine Learning/Libraries folder. Kindly correct it by placing all the files of introduction to numpy in folder and create a PR again. But that won't be labelled, as scores and program is labelled for this PR. You can just save all the files and create PR once again. @suy1968

**Comment by suy1968** [comment]
> Oops, I didn't check properly, got mistaked. You haven't created a project folder of "Introduction to Numpy" and uploaded all the files instead you had placed it all individually in Machine Learning/Libraries folder. Kindly correct it by placing all the files of introduction to numpy in folder and create a PR again. But that won't be labelled, as scores and program is labelled for this PR. You can just save all the files and create PR once again. @suy1968

Okay maam @prathimacode-hub

**Pull request merged**
