### PR TITLE
Ridge Regression #93

### PR DESCRIPTION
**Pull request by ayushi424**
## Ridge Regression  #93 
Adding practical implementation of **Ridge Regression Algorithm** using a project as  **Air Quality Prediction** as per the project structure mentioned.

- [x] DevIncept Participant 
- [x] Contributor

Closes: #93 

### Describe the changes you've made

- Added **Ridge Regression** folder in **Algorithms** folder of  **Machine Learning** folder which contains-:
1.  README.md file with proper documentation and 
2. ridge_regression.ipynb file with practical implementation.
3. Images folder with all code images.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Performance done by accuracy check and error check.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — APPROVED** [review]
As usual spot on execution. Good justification to the project. Fab. 🏆✔@ayushi424

**Comment by prathimacode-hub** [comment]
Kindly fill up the PR form with link for this PR. You haven't done yet. @ayushi424

**Comment by ayushi424** [comment]
> Kindly fill up the PR form with link for this PR. You haven't done yet. @ayushi424

@prathimacode-hub, 
I already filled the form on 8 aug'21, might be some issue.
I have filled it again :)

**Comment by prathimacode-hub** [comment]
Ok, I did ask as I couldn't see up this PR link. Not sure of why i didn't show up when it's filled earlier. Glad it's done now. Kudos to you. :-)

**Pull request merged**
