### PR TITLE
YouTube Comments Analyser

### PR DESCRIPTION
**Pull request by hrugved06**
## YouTube Comments Analyser #14 

- Created and implemented the YT comments analyser with a proper documentation 

- [x] DevIncept Participant 
- [x] Contributor

Closes: #23  

### Describe the changes you've made

- Created and implemented a model which classifies harmful comments and also converts spammed links into texts. 
- Demo Images are added to the images folder which are used in the README.md file for explanation.
- Added dataset in the Dataset folder and also added the required files.
- Also, README is added with a proper and detailed explanation. 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Once you run the model you get to know the accuracy of the model and this model can be tested with the help of a defined classifier().

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by hrugved06** [comment]
Hey, @prathimacode-hub , I have added all the required documents to the repository, have a look. Hope it is ready to merge. 
Thank You :-D

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Project folder should be as "Youtube Comments Classifier"
The project file should be as "youtube_comments_classifier.ipynb"
In README.md , add up the references beginners can refer to while working on this project in REFERENCES section.
Also add up the accuracy you had secured in this classifier at Conclusion section in README.md and elaborate the final understanding derived out of it. 

Kindly do these changes. @hrugved06

**Review by prathimacode-hub — APPROVED** [review]
Fab and impressive work. PR approved. Whooaa, very well represented. You nailed it. 👌🤩@hrugved06

**Comment by hrugved06** [comment]
Done with the requested changes, please have a look ✌️

**Pull request merged**
