### PR TITLE
Word Tokenization Techniques in NLP

### PR DESCRIPTION
**Pull request by shivani6320**
## Word Tokenization Techniques

- I have explained various techniques for word tokenization in detail with explanation.

- [x] DevIncept Participant 
- [x] Contributor

Closes: #22 

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The project file should be as "Word_tokenization_techniques_in_NLP.ipynb"
Add appropriate comments in code wherever needed to get good understanding of the project.

Kindly do these changes. @shivani6320

**Comment by shivani6320** [comment]
@prathimacode-hub , requested changes has been done. Please check :)

**Review by prathimacode-hub — APPROVED** [review]
PR is approved. Good choice of the script. Very well justified. 🤩👏@shivani6320

**Comment by shivani6320** [comment]
Thank you @prathimacode-hub !!😃

**Pull request merged**
