### PR TITLE
Introduction to Numpy

### PR DESCRIPTION
**Pull request by suy1968**
## Introduction to Numpy

- Guidance that one needs to learn about NumPy Implementation.

- [x] DevIncept Participant 
- [x] Contributor

Closes: #112 

### Describe the changes you've made

The main intention of this repo is to educate beginners with all the concepts related to data science so that they could feel confident to apply these things learned in practical exposure.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Helps readers in giving all the guidance that one needs to learn about NumPy. Tutorial to NumPy using Sample codes. 

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly follow the proper PR template provided. @suy1968

**Comment by suy1968** [comment]
> Kindly follow the proper PR template provided and also check up with the project structure. Go through the README and GUIDELINES of the project. @suy1968

please check maam

**Comment by prathimacode-hub** [comment]
This is not the PR template. And your project doesn't have any files. Check the project structure for the project and PR template for the PR. Don't combine things. @suy1968

**Comment by suy1968** [comment]
> This is not the PR template. And your project doesn't have any files. Check the project structure for the project and PR template for the PR. Don't combine things. @suy1968

Okay Mam please check again

**Comment by prathimacode-hub** [comment]
No, it needs many files. See the project structure. I don't find any changes here. Kindly push it properly. @suy1968

**Comment by suy1968** [comment]
> No, it needs many files. See the project structure. I don't find any changes here. Kindly push it properly. @suy1968

Maam please check this again

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
You are not following the right project structure. Kindly go through the README file of the project. @suy1968

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your work is perfect. Just follow the right format. I shall make things easier for you.

Changes to be done :
Instead of Library change the folder name to "Libraries"
The readme file of this project should be as README.md
The project file should be as "introduction_to_numpy.ipynb"
Also in references in README.md, do add more references for beginners to look upto.

Kindly do these changes. @suy1968

**Comment by suy1968** [comment]
> Your work is perfect. Just follow the right format. I shall make things easier for you.
> 
> Changes to be done :
> Instead of Library change the folder name to "Libraries"
> The readme file of this project should be as README.md
> The project file should be as "introduction_to_numpy.ipynb"
> Also in references in README.md, do add more references for beginners to look upto.
> 
> Kindly do these changes. @suy1968

Maam please check i am create new PR and i make also changes that you say here maam

**Pull request closed without merging**
