### PR TITLE
K Medoid Based Clustering

### PR DESCRIPTION
**Pull request by photon149**
## Related Issue 

- Info about the related issue 

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

Closes: #147   issue number that will be closed through this PR

### Describe the add-ons or changes you've made

We implemented K Medoids Clustering Algorithm , on a randomly generated dataset .We also compared the K Medoids Accuracy some other Clustering Algorithms

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manually run and tested 

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README can be elaborated. @photon149

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add advantages, description, why it's used to consider, where it can be used, overall summary. @photon149

**Comment by photon149** [comment]
Done with the suggested changes  , Please check

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Congrats on completing your challenge. Yayy. High spirit from you. Great work. ✨✔👌@photon149

**Pull request merged**
