### PR TITLE
Gnerative Adversarial Networks

### PR DESCRIPTION
**Pull request by avinash-218**
## Related Issue 

- Info about the related issue 

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

Closes: #101 

### Describe the changes you've made

- Added notebook
- Added README.md

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I verified the notebook by running successfully

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whenever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [] My changes generate no new warnings.
- [ ] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
I think coding blocks haven't been compiled in .ipynb file and also change the PR title to your issue title. @avinash-218

**Comment by avinash-218** [comment]
@prathimacode-hub Changes done. Please verify now

**Comment by prathimacode-hub** [comment]
Hey it has both issue projects in one. Lets merge one after other. No in this PR, add files only related to Generative Adversarial Networks. @avinash-218

**Comment by avinash-218** [comment]
> Hey it has both issue projects in one. Lets merge one after other. No in this PR, add files only related to Generative Adversarial Networks. @avinash-218

sorry for the inconvenience ma'am this is my first contribution.

**Comment by avinash-218** [comment]
@prathimacode-hub please verify now

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub please verify now

No worries. @avinash-218. That's how you learn right.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly go through the project structure in a way files should be added. @avinash-218

**Comment by avinash-218** [comment]
image

I know how to branch and all.
I couldn't get what is feature branch.
Could you please explain?

**Comment by avinash-218** [comment]
Sorry for the inconvenience. I have created a feature branch and requested another pull request.
Assign me there under hacktoberfest`21 program and let me know any changes to undergo.

**Pull request closed without merging**
