### PR TITLE
Social Distance Detection #116

### PR DESCRIPTION
**Pull request by anubhav201241**
- Info about the related issue 
Social Distance Detection using Computer Vision, Open Cv and Python 

- [x] DevIncept Participant 
- [ ] Contributor

Closes: #116 

### Describe the changes you've made
Created a file Social Distance Detection using Open cv and Python 

Give a clear description what modifications you have made

Modified the Social Distance detection file and add the yolo and coco module in it 

## How Has This Been Tested?

Describe how have you verified the changes made
I have tested the code in Pycharm 

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.Issue no: #116  

Created the PR for Social Distance Detection which detects the people distance while they are maintain the distance or not using Python and Open cv

@prathimacode-hub Kindly Review it and Merge it :)

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Sorry to say, but you are not following right project structure. And every repo has its own guidelines and structure to follow. Always go throught the README file for better understanding of things. If any queries, don't hesitate to ask. @anubhav201241

**Comment by anubhav201241** [comment]
I have go through the readme and made the PR as you have mentioned in your readme. Please be specific what I have to do now what I have done wrong?

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
This is a computer vision project so it should go under "/Computer Vision/Tutorials" folder.

Changes to be done:
In "/Computer Vision/Tutorials" folder, create a project folder titled "Social Distance Detection"
"coco.names" file is a dataset, so it should go under "Dataset" folder
The other folder you need to add in this project folder is "Model" folder
Here in this you would be adding your model "yolov3.cfg"
There is video file of .mp4 which should go in "Media" folder. Along with it also add the output screenshot images in it.
The project file should be titled as "social_distance_detection.iynb" and it should be in .ipynb format. Also the project file should have appropriate comments in code to get good understanding of the project. This project file should be in "Model" folder
Other than that, we need a "requirements.txt" file whee you list out all the libraries imported in this project
Now at last comes README file, which should be as "README.md". There is README template to follow. You can check it [here](https://github.com/prathimacode-hub/DS-ScriptsNook/blob/main/.github/readme_template.md). Be elaborative always and also make sure you add up the images and video file in screenshot section along with all the asked things that needs to be shown in README file. 
The main intention of repo is to make a beginner friendly repository who is thinking of learning datascience in efficient way. It's kinda tutorial. Always give enough briefing wherever required.

This is the project structure mentioned in README file of the project if you had read it. Kindly do all these changes. @anubhav201241

**Comment by anubhav201241** [comment]
What if I have done this project on pycharm or vscode and don't done it in google Collab why should I add .pynb file when my code is running fine in .oh format

**Comment by prathimacode-hub** [comment]
What's the problem you're facing now? Are you willing to do the changes or not? @anubhav201241

**Comment by anubhav201241** [comment]
I'm not facing any problem my code is all running fine but I don't know why you are saying for .pynb file it is working fine in .py file then why should I change

**Comment by prathimacode-hub** [comment]
I'm not wronging you here, you had done right but according to the guidelines mentioned it should be followed. If i accept this now, it wou;d be unfair for others as all followed up with the same guidelines given. There is a proper project structure to be maintained for good open source contribution and maintain uniformity across all. @anubhav201241

**Comment by anubhav201241** [comment]
I think you did not get my point I'm only talking about why not .py file why only .ipynb file must be there when .py file is also a python file and working properly then why should I do it on Collab in Collab live camera and opencv is tough to use so that's why I use simple pycharm editor for running my code.

**Comment by prathimacode-hub** [comment]
Ok fine i will accept .py file happy? But atleast do the changes addressed with respect to the project structure mentioned. @anubhav201241

**Comment by prathimacode-hub** [comment]
I don't think you are interested to do the changes, All it matters is why .ipynb file instead of .py file. I said today is the last date to merge PR's still you haven't done any changes addressed even after saying I will accept .py file. @anubhav201241

**Comment by anubhav201241** [comment]
I'm  busy in doing these changes

**Comment by prathimacode-hub** [comment]
By when would it get done? @anubhav201241

**Comment by anubhav201241** [comment]
11.30

**Comment by prathimacode-hub** [comment]
But how would I know if you are interested unless you dont say it expect 1 thing you point out. And today is last date to merge PR and its already 11pm. I have to hit the bed and here I am waiting. @anubhav201241

**Comment by prathimacode-hub** [comment]
You also have to do the change in PR created at "PyAlgo-Tree"

**Comment by anubhav201241** [comment]
I have made another commit only i did not include readme file in it but uploaded it in computer vision folder

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
No, I said clearly it should be in "/Computer Vision/Tutorials folder and also addressed many changes.
Not all changes are done yet. And README.md file is must. I can't wait anymore. I should hang on to sleep. @anubhav201241

**Comment by anubhav201241** [comment]
Ok 🙂

**Comment by prathimacode-hub** [comment]
Try to do the changes for your PR by early morning. @anubhav201241

**Comment by prathimacode-hub** [comment]
No update still. I don't even know what to say to you. There are still many changes to be done which you haven't. You asked me to list out and I did. I am halting up the things for you. But I am sorry, I can't held it any longer. You can do the changes leisurely when you have time. I have to remove the label. Its so late. Team is asking up for the score card. I requested some time for you, so that you could turn these things up. Now they won't wait any further. @anubhav201241

**Comment by prathimacode-hub** [comment]
Why did you close the PR? You should not close it from your end. Atleast responding is courtesy. I had waited for so long. I just removed the label not assignment hoping you would turn up the PR. Is it that all it matters for you is only scores? I thought you would atleast do the changes asked. But no. I also obliged to you by giving exception. This is what I get in return? @anubhav201241

**Comment by anubhav201241** [comment]
So you have said that time is up then why are you saying this of you don't want to merge I'm saying that it is not matter that much I have contributed to different project also and they do not forced me to do these things and I have already attached all my code file already created readme contributed my whole day to this but at last what response I'm getting from your side and at last you have also removed the dcp label then what is the point to contribute to your repo.

**Comment by prathimacode-hub** [comment]
Yes, time is up. I removed label not assignment. I am not pointing you wrong, but you can easily do up the changes right. Every repo has its own requirements. All did follow up the same. Still i gave you exception for few things and you are contributing only for scores? Then this is not open source. I am getting msgs from team to submit the scores. Its now 4pm and I didn't send up the scores hoping you would turn up with changes.  That's Ok. I don't want to make it big or argue further. I am just being nice to you. I have provided all the points needed for changes. if you don't want to do it's upto you. You could have easily said that I don't want to work on changes. Simple. Instead of countering back. I never forced you. I just addressed the things that needs to be corrected. @anubhav201241

**Pull request closed without merging**
