### PR TITLE
Color Detection using OpenCV

### PR DESCRIPTION
**Pull request by vishvarana**
Related Issue
Color Detection in images using python library

 √DevIncept Participant
√ Contributor

Closes: #27 

Describe the changes you've made
Added Color Detection using OpenCV project

Type of change
What sort of change have you made: Feature added

   Bug fix (non-breaking change which fixes an issue)
 √New feature (non-breaking change which adds functionality)
   Code style update (formatting, local variables)
   Breaking change (fix or feature that would cause existing functionality to not work as expected)
   This change requires a documentation update

How Has This Been Tested?
I have provided different blocks of code to detect colors and also finding images with a particular color in it

Describe how have you verified the changes made
By different blocks of code and test cases

Checklist:
 √My code follows the guidelines of this project.
√ I have performed a self-review of my own code.
 √I have commented my code, particularly wherever it was hard to understand.
√ I have made corresponding changes to the documentation.
 √My changes generate no new warnings.
√ I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by vishvarana** [comment]
I am sorry for closing the previous PR, I didn't have idea about it. I made a major mistake hence I made a different branch for requesting changes. I'll surely take care of it next time. Please review this PR and let me know if any changes required.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The project title should be as "Color Detection using OpenCV". Since this is the explanation of the concept along with sample project. This should go under "/Computer Vision/Tutorials" repository.
Your README.md needs more elaboration. It's like one line answers. The main intention of this repo is to educate beginners with concepts along with sample project. When a issue is taken, it should cover everything regarding the same. That means, you should provide all the details concerning "Color Detection using OpenCV"
And in README.md, references means you have to provide the links you had referred while working on this project and also the links which would help beginners explore more deeply into this concept.
All images and output screenshots should be in "Images" folder
The "requirements.txt" file is needed which would list out all the libraries you had used for this sample project. 
You should also provide a descriptive conclusion derived out of this issue. 
Along with it, the project file should have appropriate comments in code to get good understanding of the project.

Kindly do these needful changes. @vishvarana

**Comment by prathimacode-hub** [comment]
> I am sorry for closing the previous PR, I didn't have idea about it. I made a major mistake hence I made a different branch for requesting changes. I'll surely take care of it next time. Please review this PR and let me know if any changes required.

No worries, as long as you don't repeat it next time. @vishvarana

**Comment by prathimacode-hub** [comment]
Kindly do the addressed changes. @vishvarana

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your things and works are right. But formats are not right with respect to project structure. I shall make things easier for you.

Changes to be done:
The project folder should be as "Color Detection using Open CV"
All images and output screenshots should be in "Images" folder
The project file of .ipynb should be in "Model" folder
In requirements file all those things aren't needed, all we need is only list of libraries used in this project in an order with the version number. This files helps beginners in directly installing all the libraries at a time instead of installing them one by one. 

Kindly do these changes. @vishvarana

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Only changes it needs, all images  and output screenshots should be in "Images" folder. @vishvarana

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Yayy. Congrats on your first PR and welcome to the repo officially. Great start. Keep rising high. ✨🎉👏@vishvarana

**Review by prathimacode-hub — COMMENTED** [review]
Oops, your changes are shown here in PR but it didn't load up once its merged. I guess you haave to do the PR again. But label is assigned here so it won't be assigned again. Kindly create a PR once again but with the changes discussed appropriately. I hope you must have saved the earlier files. @vishvarana

**Pull request merged**
