### PR TITLE
Added Random Forest Classifier Algorithm

### PR DESCRIPTION
**Pull request by vaishnavipatil4848**
- [x] DevIncept Participant
- [ ] Contributor

Closes: #6 

Describe the changes you've made
Give a clear description what modifications you have made
* Added Random Forest Classifier Algorithm.
* Practically implemented on a real world Dataset.
* Created  Explanation and Documentation for the same .

Type of change
What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] This change requires a documentation update
How Has This Been Tested?
Describe how have you verified the changes made

Checklist:
 - [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x]  My changes generate no new warnings.
 - [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Please follow the PR template given to your comment above and do the changes accordingly and also add up the issue number you worked on. @vaishnavipatil4848

**Comment by vaishnavipatil4848** [comment]
I have made changes as per the given PR Template . Thank you.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
In README.md file for working conditions, add step by step procedure using points along with images you had provided.
Also elaborate more in usage section.
Add your full name at the end of the file. @vaishnavipatil4848

**Comment by vaishnavipatil4848** [comment]
I have made all the requested changes and updated the README file.

**Comment by prathimacode-hub** [comment]
Hey in the form you had added the issue link instead of PR link. Kindly change it. @vaishnavipatil4848

**Comment by vaishnavipatil4848** [comment]
I have changed it . Please check.

**Pull request merged**
