### PR TITLE
Live Barcode and QR Code Reader

### PR DESCRIPTION
**Pull request by hrugved06**
## Live Barcode and QR Code Reader

- Implemented real-time QR/Barcode Scanner model with all the details.

- [x] DevIncept Participant 
- [x] Contributor

Closes: #107 

### Describe the changes you've made

- Created and implemented a model which scans the QR/Barcode and saves the result in the .txt file
- Demo Images are added to the images folder which is used in the README.md file for explanation.
- This is a real-time scanning model
- Also, README is added with a proper and detailed explanation. 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

It is a real-time QR/Barcode scanner and working of it is added in the [README](https://github.com/DevIncept-Contribution-Program-21/DS-ScriptsNook/blob/main/Computer%20Vision/Live%20Barcode%20and%20QR%20Code%20Reader/README.md)

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by hrugved06** [comment]
Hey, @prathimacode-hub  , I have added all the required documents to the repository, have a look. Hope it is ready to merge.
Thank You :-D

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Kindly add your project of "Live Barcode and QR Code Reader" in "/Computer Vision/Tutorials" folder
The project files should be in .ipynb format and file name should be as "file_name.ipynb"
Add appropriate comments in code to get good understanding of the project. 
Also in README.md I could only see the barcode explanation but no QR code explanation in every section of it. 

Kindly do these needful changes. @hrugved06

**Comment by hrugved06** [comment]
> Changes to be done:
> Kindly add your project of "Live Barcode and QR Code Reader" in "/Computer Vision/Tutorials" folder
> The project files should be in .ipynb format and file name should be as "file_name.ipynb"
> Add appropriate comments in code to get good understanding of the project.
> Also in README.md I could only see the barcode explanation but no QR code explanation in every section of it.
> 
> Kindly do these needful changes. @hrugved06

Requested changes done.

Note:
- QR code and Barcode Example is added in the Conclusion.
- As this task is performed in a local environment there is need of .py file so I kept that file too along with the .ipynb file

**Review by prathimacode-hub — APPROVED** [review]
Ok, very well justified work. You're doing an exceptional work. Keep rocking. 👌🤩@hrugved06

**Pull request merged**
